routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('/', [
        'as'   => 'index',
        'uses' => 'HomeController@index',
    ]
);


Route::get('/contact', [
        'as'   => 'contact',
        'uses' => 'HomeController@contact',
    ]
);

Route::get('/gallery', [
        'as'   => 'gallery',
        'uses' => 'HomeController@gallery',
    ]
);


Route::get('/posts/{category}', [
        'as'   => 'posts.index',
        'uses' => 'PostController@index',
    ]
);

Route::get('/page/{slug}', [
        'as'   => 'page',
        'uses' => 'PageController@index',
    ]
);

Route::get('/search', [
        'as'   => 'posts.search',
        'uses' => 'PostController@search',
    ]
);

Route::get('/posts/{category}/{slug}', [
        'as'   => 'post.show',
        'uses' => 'PostController@show',
    ]
)->where('slug', '[A-Za-z0-9-_]+');

Route::post('/contact/feedback', [
        'as'   => 'contact.feedback',
        'uses' => 'HomeController@feedback',
    ]
);

Route::post('/newsletter', [
        'as'   => 'newsletter',
        'uses' => 'HomeController@newsletter',
    ]
);

Route::post('/post/comment/{id}', [
    'as'   => 'post.comment',
    'uses' => 'PostController@comment',
]);

 Route::group(['prefix' => 'admin',
               'middleware' => ['admin'],
               'namespace' => 'Admin'], function()
 {
     CRUD::resource('menu-item', 'MenuItemCrudController');
     CRUD::resource('post', 'PostCrudController');
     CRUD::resource('category', 'CategoryCrudController');
//     CRUD::resource('info', 'InfoCrudController');
     Route::get('/settings', [
         'as'   => 'settings',
         'uses' => 'InfoCrudController@edit',
     ]);
     Route::put('/info/1', [
         'uses' => 'InfoCrudController@update',
     ]);

     Route::get('/user', [
         'as'   => 'user',
         'uses' => 'UserCrudController@edit',
     ]);
     Route::put('/user/1', [
         'uses' => 'UserCrudController@update',
     ]);

     CRUD::resource('feedback', 'FeedbackCrudController');
     CRUD::resource('comments', 'CommentsCrudController');
     CRUD::resource('newsletter', 'NewsletterCrudController');
     CRUD::resource('social', 'SocialCrudController');
     Route::get('/edit-account-info', [
         'as'   => 'backpack.account.info',
         'uses' => 'MyEditAccountController@getAccountInfoForm',
     ]);
     Route::post('/edit-account-info', [
         'as'   => 'backpack.account.edit.info',
         'uses' => 'MyEditAccountController@postAccountInfoForm',
     ]);
     Route::get('/change-password', [
         'as'   => 'backpack.account.password',
         'uses' => 'MyEditAccountController@getChangePasswordForm',
     ]);
     Route::post('/change-password', [
         'as'   => 'backpack.account.edit.password',
         'uses' => 'MyEditAccountController@postChangePasswordForm',
     ]);

});

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use App\Models\Comments;
use App\Models\Post;
use Illuminate\Http\Request;


class PostController extends Controller
{
    /**
     * Категория
     *
     * @param $slug
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index($slug)
    {
        $category = Category::where('slug', $slug)->first();
        if ($category) {
            $posts = Post::whereHas('category', function($query) use ($slug) {
                $query->where('slug', $slug);
            })->where('status','Опубликовано')->latest('created_at')->paginate(6);
        }


        return $category ? view('category', compact('posts', 'category'))
            : abort(404);
    }

    /**
     * Пост
     *
     * @param $category
     * @param $slug
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show($category, $slug)
    {
        $post = Post::where('slug', $slug)->with('category')->whereHas('category', function($query) use ($category) {
            $query->where('slug', $category);
        })->withCount('comments')->where('status','Опубликовано')->first();
        $comments = Comments::where('post_id', $post->id)->get();

        return view('single', compact('post', 'comments'));
    }

    /**
     * Поиск
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function search(Request $request)
    {

        $search = $request->input('search');

        $posts = Post::where('title','LIKE','%'.$search.'%')
            ->orwhere('text','LIKE','%'.$search.'%')
            ->with('category')
            ->get();
//            ->paginate(10);

        return $search == 'Найти..' ? redirect()->back() : view('search', compact('posts', 'search'));

    }

    public function comment(Request $request, $id)
    {
        $data = $request->all();
        $data['post_id'] = $id;
        Comments::create($data);
        return redirect()->back();

    }

}

resources/views/category.blade.php
@extends('layouts.app')

@section('title', 'SURF')

@section('content')

    <div class="banner-1" style="background: url({{'/images/'.$info->image_slider}})">

    </div>

    <!-- technology-left -->
    <div class="technology">
        <div class="container">
            <div class="col-md-9 technology-left">
                <div class="blog">

                    <h2 class="w3">{{$category->name}}</h2>
                    <p style="padding-top: 30px; color: #777; font-size: 0.875em; line-height: 1.8em; margin: 1em 0;">{!! $category->description !!}</p>
                    @php($i = 1)
                    @foreach($posts as $post)
                        @if ($i%2!=0)
                    <div class="blog-grids1">
                        @endif
                        <div class="col-md-6 blog-grid">
                            <div class="blog-grid-left1">
                                <a href="{{route('post.show', [$category->slug, $post->slug])}}"><img src="{{asset('images/posts/'.$post->image)}}" alt=" " class="img-responsive"></a>
                            </div>
                            <div class="blog-grid-right1">
                                <a href="{{route('post.show', [$category->slug, $post->slug])}}">{{$post->title}}</a>
                                <h4>{{ \Carbon\Carbon::parse($post->created_at)->format('d.m.y')}}</h4>
                                <p>{!! str_limit($post->text, $limit = 100, $end = '...') !!} </p>
                            </div>
                            <div class="clearfix"> </div>
                            <div class="more m1">
                                <a type="button" href="{{route('post.show', [$category->slug, $post->slug])}}" class="btn btn-1 btn-default">Далее</a>
                            </div>
                        </div>
                        @if ($i%2==0 || ($i%2!=0 && $i==count($posts)))
                        <div class="clearfix"> </div>
                    </div>
                        @endif
                        @php($i++)
                    @endforeach

                    <nav class="paging">
                        {{ $posts->links() }}
                    </nav>

                </div>
            </div>
            @include('layouts.right-bar')
        </div>
    </div>


@endsection

resources/views/contact.blade.php
@extends('layouts.app')

@section('title', 'SURF')

@section('content')

    <div class="banner-1" style="background: url({{'/images/'.$info->image_slider}})">

    </div>

    <!-- technology-left -->
    <div class="technology">
        <div class="container">
            <div class="col-md-9 technology-left">
                <div class="contact-section">
                    <h2 class="w3">Контакты</h2>


                    <div class="contact-grids">
                        <div class="col-md-8 contact-grid">

                            <p>{!! $info->desc_contact !!}</p>
                            <form action="{{ route('contact.feedback', [], false) }}" method="post">

                                <input type="hidden" name="_token" value="{{ csrf_token() }}"/>
                                <input type="text" name="name"  required placeholder="Имя"/>
                                <input type="email" name="email"  required placeholder="Email"/>
                                <textarea type="text" name="message" required placeholder="Сообщение..."></textarea>
                                <input type="submit" value="Отправить">
                            </form>
                        </div>
                        <div class="col-md-4 contact-grid1">
                            {{--<h4>Контактные данные</h4>--}}
                            <div class="contact-top">

                                <div class="clearfix"></div>
                            </div>
                            <ul>
                                {{--<li><i class="glyphicon glyphicon-earphone" aria-hidden="true"></i> Office : 0041-456-3692</li>--}}
                                @if($user->phone)
                                <li><i class="glyphicon glyphicon-phone" aria-hidden="true"></i> Mobile : {{$user->phone}}</li>
                                @endif
                                <li><i class="glyphicon glyphicon-envelope" aria-hidden="true"></i> <a href="#"></a><a href="mailto:{{$user->email}}">{{$user->email}}</a></li>

                                {{--<li><i class="glyphicon glyphicon-print" aria-hidden="true"></i> Fax : 0091-789-456100</li>--}}
                            </ul>


                        </div>

                        <div class="clearfix"></div>
                    </div>

                    {{--<div class="google-map">--}}
                        {{--<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d424145.8679554096!2d150.65178930803913!3d-33.847403996396665!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6b129838f39a743f%3A0x3017d681632a850!2sSydney+NSW%2C+Australia!5e0!3m2!1sen!2sin!4v1470643502584" allowfullscreen></iframe>--}}
                    {{--</div>--}}

                </div>

            </div>

            @include('layouts.right-bar')
        </div>
    </div>

@endsection

resources/views/gallery.blade.php
@extends('layouts.app')

@section('title', 'SURF')

@section('content')

    <div class="banner-1" style="background: url({{'/images/'.$info->image_slider}})">

    </div>

    <!-- technology-left -->
    <div class="technology">
        <div class="container">
            <div class="col-md-9 technology-left">
                <div class="gallery" id="gallery">

                    <h2 class="w3">Галлерея</h2>
                    <p>{!! $info->desc_gallery !!}</p>
                    <div class="gallery-grids">
                        @foreach($posts as $post)
                        <div class="gallery-grid">
                            <a href="{{route('post.show', [$post->category->slug, $post->slug])}}" class="wow fadeInUp animated animated" data-wow-delay=".5s" style="visibility: visible; animation-delay: 0.5s; animation-name: fadeInUp;">
                                <img src="images/posts/{{$post->image}}" alt=" " class="img-responsive zoom-img">
                            </a>
                        </div>
                        @endforeach
                        <div class="clearfix"> </div>
                    </div>

                </div>
            </div>
            @include('layouts.right-bar')
        </div>
    </div>
@endsection

resources/views/page.blade.php
@extends('layouts.app')

@section('title', 'SURF')

@section('content')

    <div class="banner-1" style="background: url({{'/images/'.$info->image_slider}})">

    </div>

    <!-- technology-left -->
    <div class="technology">
        <div class="container">
            <div class="col-md-9 technology-left">
                <div class="w3agile-1">
                    <div class="welcome">
                        <div class="welcome-top heading">
                        <h2 class="w3">{{$page->name}}</h2>
                        {!! $page->content !!}
                    </div>
                </div>
            </div>
        </div>
            @include('layouts.right-bar')
    </div>
    </div>


@endsection

resources/views/search.blade.php
@extends('layouts.app')

@section('title', 'SURF')

@section('content')

    <div class="banner-1" style="background: url({{'/images/'.$info->image_slider}})">

    </div>

    <!-- technology-left -->
    <div class="technology">
        <div class="container">
            <div class="col-md-9 technology-left">
                <div class="blog">

                    <h2 class="w3"> Поиск по запросу: {{$search}}</h2>
                    @if(count($posts)>0)
                        @php($i = 1)
                        @foreach($posts as $post)
                            @if ($i%2!=0)
                                <div class="blog-grids1">
                                    @endif
                                    <div class="col-md-6 blog-grid">
                                        <div class="blog-grid-left1">
                                            <a href="{{route('post.show', [$post->category->slug, $post->slug])}}"><img
                                                        src="{{asset('images/posts/'.$post->image)}}" alt=" "
                                                        class="img-responsive"></a>
                                        </div>
                                        <div class="blog-grid-right1">
                                            <a href="{{route('post.show', [$post->category->slug, $post->slug])}}">{{$post->title}}</a>
                                            <h4>{{ \Carbon\Carbon::parse($post->created_at)->format('d.m.y')}}</h4>
                                            <p>{!! str_limit($post->text, $limit = 100, $end = '...')  !!}</p>
                                        </div>
                                        <div class="clearfix"></div>
                                        <div class="more m1">
                                            <a type="button"
                                               href="{{route('post.show', [$post->category->slug, $post->slug])}}"
                                               class="btn btn-1 btn-default">Далее</a>
                                        </div>
                                    </div>
                                    @if ($i%2==0 || ($i%2!=0 && $i==count($posts)))
                                        <div class="clearfix"></div>
                                </div>
                                    @endif
                            @php($i++)

                        @endforeach
                    @else
                        <div class="help-block">
                            <p>Извините, ничего не найдено:(</p>
                        </div>
                    @endif

                </div>
            </div>
            @include('layouts.right-bar')
            {{--<nav class="paging">--}}
                {{--{{ $posts->links() }}--}}
            {{--</nav>--}}
        </div>

    </div>



@endsection

resources/views/single.blade.php
@extends('layouts.app')

@section('title', 'SURF')

@section('content')
    <div class="banner-1" style="background: url({{'/images/'.$info->image_slider}})">

    </div>

    <!-- technology-left -->
    <div class="technology">
        <div class="container">
            <div class="col-md-9 technology-left">
                <div class="agileinfo">

                    <h2 class="w3">{{$post->title}}</h2>
                    <div class="single">
                        <img src="{{asset('images/posts/'.$post->image)}}" class="img-responsive" alt="">
                        <div class="b-bottom">
                            <h5 class="top">{{$post->title}}</h5>
                            <p class="sub">{!! $post->text !!}</p>
                            <p>{{ \Carbon\Carbon::parse($post->created_at)->format('d.m.y')}}
                                <a class="span_link" ><span class="glyphicon glyphicon-comment"></span>{{$post->comments_count}} </a>
                            </p>

                        </div>
                    </div>


                    @if(count($comments)>0)
                    <div class="response">
                        <h4>Комментарии</h4>
                        @foreach($comments as $comment)
                        <div class="media response-info">

                            <div class="media-left response-text-left">
                                <a href="#">
                                    <img src="{{ \Laravolt\Avatar\Facade::create($comment->name)}}"  alt="">
                                </a>
                            </div>
                            <div class="media-body response-text-right">
                                <ul>
                                    <li><p class="nickname">{{$comment->name}}</li>
                                    <li class="date">{{ \Carbon\Carbon::parse($comment->created_at)->format('d.m.y H:i')}}</li>
                                </ul>
                                <p>{{$comment->message}}</p>
                            </div>
                                <div class="clearfix"> </div>
                        </div>
                        @endforeach
                    </div>
                    @endif
                    <div class="coment-form">
                        <h4>Добавьте комментарий</h4>
                        <form method="post" action="{{ route('post.comment', [$post->id], false) }}">
                            <input type="hidden" name="_token" value="{{ csrf_token() }}"/>
                            <input type="text"  name="name" placeholder="Имя" required/>
                            <textarea name="message" required placeholder="Комментарий..."></textarea>
                            <input type="submit" value="Отправить">
                        </form>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
            @include('layouts.right-bar')
        </div>
    </div>


@endsection